version: "3"
services:
  domoticz:
    container_name: domoticz
    build: ./
    volumes:
       - backups:/home/domoticz/stable/backups
    environment:
       - "TZ=Europe/Minsk"       
    restart: unless-stopped
    network_mode: "host"
    privileged: true
volumes:
  backups: